### ISSUE TITLE
Compile and Installation error using cygwin64

### ISSUE THREAD

**Issue by furqan-ops** [alexkreidler/hydra-view#6]
Please Help i cannot install hydra password cracker using cygwin64
Below are pics
![1](https://user-images.githubusercontent.com/60847168/116804176-26a71580-ab36-11eb-9591-848b45b323c5.JPG)
![2](https://user-images.githubusercontent.com/60847168/116804177-29096f80-ab36-11eb-8945-579281deb4c5.JPG)
![3](https://user-images.githubusercontent.com/60847168/116804178-29a20600-ab36-11eb-9db8-ce438f95a69d.JPG)

**Comment by alexkreidler** [comment]
Closing as this is the wrong repo.
